#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

#define MUGSHOT_START    0

#define MUGSHOT_TEST    0
#define MUGSHOT_TEST2   1
#define MUGSHOT_MAJO    2
#define MUGSHOT_END     2

#define MUGSHOT_COUNT   (MUGSHOT_END - MUGSHOT_START + 1)

#endif //GUARD_CONSTANTS_MUGSHOTS_H