#ifndef GUARD_CONSTANTS_TALENTS_H
#define GUARD_CONSTANTS_TALENTS_H

#define TALENT_NONE         0
#define TALENT_UNKNOWN      1

#define LOCKED_TALENTS_CANT_BE_RANDOMED TALENT_UNKNOWN

#define TALENT_DREAMWALKER          LOCKED_TALENTS_CANT_BE_RANDOMED + 1
#define TALENT_OVERLOADED           LOCKED_TALENTS_CANT_BE_RANDOMED + 1


#endif //GUARD_CONSTANTS_TALENTS_H